---
title: "In_vivo_FRET"
author: "Ryan Martin"
output: html_document
---

## Required libraries 
library(tidyverse)
library(modelr)
library(readxl)

## Set working directory
setwd("~/directory")

##Set recording interval time
interval_time <- 2

##Set length of baseline reading
baseline_time <- 10

##List of files in directory
files <- list.files(pattern = "*.xls", full.names = T, recursive = T)

##Import CFP and YFP channel readings and name elements of list
all_cfp <- map(files, read_xls, sheet = 4)
names(all_cfp) <- gsub(".*/(.*)\\..*", "\\1", files)

all_yfp <- map(files, read_xls, sheet = 5)
names(all_yfp) <- gsub(".*/(.*)\\..*", "\\1", files)

## Average  CFP readings from control animals and do linear regression
gather_fluorescence <- function(n, z) {
    gather(n, Time, Fluorescence, 2:ncol(n)) %>%
    group_by(Time) %>%
    summarise(Fluorescence = mean(Fluorescence)) 
}

##Calculate CFP and YFP mean fluorescence at each time point for the control files 
control_cfp <- map(all_cfp[grep("Control", files)], gather_fluorescence) 
control_yfp <- map(all_yfp[grep("Control", files)], gather_fluorescence)

control_cfp <- unique(control_cfp)
control_yfp <- unique(control_yfp)

## Take  CFP readings from control animals and do linear regression
control_cfp_linear <- control_cfp %>%
                        reduce(left_join, by = "Time") %>%
                        gather(Fluorescence, value, Fluorescence.x:Fluorescence.y) %>%
                        mutate(Time = as.numeric(factor(Time)) * interval_time)

linear_cfp <- lm(value ~ Time, data = control_cfp_linear)

background_cfp <- select(control_cfp_linear, Time) %>%
                    distinct() %>%
                    add_predictions(linear_cfp)

## Take  YFP readings from control animals and do linear regression
control_yfp_linear <- control_yfp %>%
                        reduce(left_join, by = "Time") %>%
                        mutate(Time = as.numeric(factor(Time)) * interval_time) %>%
                        gather(Fluorescence, value, Fluorescence.x:Fluorescence.y)

linear_yfp <- lm(value ~ Time, data = control_yfp_linear)

background_yfp <- select(control_yfp_linear, Time) %>%
                    distinct() %>%
                    add_predictions(linear_yfp)

## Extract datasets of treated animals in the list and name them
treat_cfp <- map(all_cfp[grep("Control", files, invert = T)], gather_fluorescence)
treat_yfp <- map(all_yfp[grep("Control", files, invert = T)], gather_fluorescence)

##Adjust CFP and YFP but substracting off predicted values from control linear regression
adj_cfp <- map(treat_cfp, function(x) {
    mutate(x, Time = as.numeric(factor(Time)) * interval_time) %>%
    left_join(background_cfp, by = "Time")  %>%
    mutate(fluorescence_adj = Fluorescence - pred) %>%
    select(Time, fluorescence_adj)
})

adj_yfp <- map(treat_yfp, function(x) {
    mutate(x, Time = as.numeric(factor(Time)) * interval_time) %>%
    left_join(background_yfp, by = "Time")  %>%
    mutate(fluorescence_adj = Fluorescence - pred) %>%
    select(Time, fluorescence_adj)
})

##Merge CFP and YFP channels into one matrix
merged_adj <- list()

for(i in 1:length(adj_cfp)) {
  a <- adj_cfp[i][[1]]
  b <- adj_yfp[i][[1]]
  merged_adj[i][[1]] <- left_join(a, b, by = "Time")
}

##Collapse list into one matrix
prediction_function <- plyr::ldply(merged_adj) %>%
  rename(fluorescence_adj = fluorescence_adj.x) %>%
  filter(fluorescence_adj > 0 & fluorescence_adj.y > 0)

nonlinear <- nls(fluorescence_adj.y ~ x*(fluorescence_adj^b), data = prediction_function, start = list(x = 0.5, b = 1.1))

predicted_yfp <- map(adj_cfp, function(x) {
  add_predictions(x, nonlinear, var = "predicted_yfp") 
})


## Obtain baseline fluorescence for each animal
treat_baseline <- map(merged_adj,  function(x) {
    mutate(x, fret = fluorescence_adj.y / fluorescence_adj.x) %>%
    filter(Time <= baseline_time) %>%
    summarise(baseline = mean(fret, na.rm = T))
})

predict_baseline <- map(predicted_yfp,  function(x) {
    mutate(x, fret = predicted_yfp / fluorescence_adj) %>%
    filter(Time <= baseline_time) %>%
    summarise(baseline = mean(fret, na.rm = T))
})

## Obtain FRET ratios for each animal
treat_ratio <- map(merged_adj, function(x) {
    mutate(x, fret = fluorescence_adj.y / fluorescence_adj.x) %>%  ##Calculate FRET ratio
    select(Time, fret)  ##Select required columns from dataset
})

predict_ratio <- map(predicted_yfp, function(x) {
    mutate(x, fret = predicted_yfp / fluorescence_adj) %>%  ##Calculate FRET ratio
    select(Time, fret)  ##Select required columns from dataset
})

## Merge FRET ratios with the baseline FRET for each animal
treat_delta_fret <- list()

for(i in 1:length(treat_ratio)) {
  a <- treat_ratio[i][[1]]
  b <- treat_baseline[i][[1]]
  treat_delta_fret[i][[1]] <- cbind(a, b)
}

predict_delta_fret <- list()

for(i in 1:length(predict_ratio)) {
  a <- predict_ratio[i][[1]]
  b <- predict_baseline[i][[1]]
  predict_delta_fret[i][[1]] <- cbind(a, b)
}

## Calculate dFRET and %dFRET/FRET
dfret <- function(x) {
    mutate(x, dfret = fret - baseline,  ##Calculate dFRET
           df_fret = dfret / fret * 100) %>% ##Calculate %dF/F
    select(Time, dfret, df_fret) ##Select required columns from dataset
}

treat_fret <- map(treat_delta_fret, dfret)
predict_fret <- map(predict_delta_fret, dfret)

##Combine predicted and treatment values
treat_predict_list <- list()

for(i in 1:length(treat_fret)) {
  treat <- treat_fret[i][[1]]
  predicted <- predict_fret[i][[1]]
  treat_predict_list[i][[1]] <- left_join(treat, predicted, by = "Time")
}

names(treat_predict_list) <- names(all_cfp[grep("Control", files, invert = T)])

treat_predict_adj <- map_dfr(treat_predict_list, .id = "names", function(x) {
  mutate(x, dfret = dfret.x - dfret.y, 
            df_fret = df_fret.x - df_fret.y) %>%
  select(Time, dfret, df_fret)
})


## Quick plot of all the animals in the current directory
ggplot(treat_predict_adj, aes(x = Time, y = df_fret, color = names)) + 
  geom_line() 


